### ISSUE TITLE
[security issue] Open links in default program instead of file explorer

### ISSUE THREAD

**Issue by arend-von-reinersdorff** [feinstaub/firefox_addon_local_filesystem_links#16]
Thanks for the Addon. It's really helpful :-)

Would it be possible to open links with the default system program? For example open .txt files with a text editor and .doc files with Word?

Usually when I follow a link, I don't want to see the file in the file explorer but open it directly.

**Comment by EnriqueSoria** [comment]
That would be great.

**Comment by feinstaub** [comment]
fixed in latest master

**Comment by feinstaub** [comment]
tooltip updated with 55c19bb4aeacdb829852c11afc60168e25ef4069

**Comment by feinstaub** [comment]
This is now implemented but it might open a security hole: some javascript could download a malicious shell script file and then use some javascript to invoke the this file with the current user's OS access rights.

**Comment by feinstaub** [comment]
TODO: Try if it is possible to do something like this:
1) Prepare a web site that contains some malicious content that will be downloaded to the Firefox web cache location (where?)
2) Prepare a link that opens the downloaded file
3) Have some Javascript that triggers this link without user interaction.

**Comment by AWolf81** [comment]
I'm still trying to find a way to trigger a malicious script that's doing something with local files but I haven't found anything. I'll continue to work on this because that's very important.

The worst thing I've found is that you can directly start the windows command prompt but the good thing here is that you can't append a command as parameter because the addon doesn't handle it correctly and displays a message that it can't open the link. (It takes everything after the last slash as file name and that doesn't exit.)

So something like `c:\windows\sysWOW64\cmd.exe /k echo run any windows command && format c:` won't work.
But if we would fix the file handling and enable passing of parameters this would be dangerous. (don't know if parameters are supported by FF API)

So here is a fiddle where I've tried to find a security hole. https://jsfiddle.net/1jwxuq6y/1/

In the fiddle I've also hidden the file links to trigger the behaviour with a timeout. I don't like that it is possible to hide the local link icons. I'll check if I can add something that these links are visible as soon as the addon adds the icon.

In this [SO question](http://stackoverflow.com/questions/5317834/workaround-for-href-file-in-firefox) there is a comment that mentions to have access to file protocol would allow a server to download something. 

For the addon that's not working because file protocol isn't enabled for ajax requests and will be only enabled after a click event on an anchor tag. So this should be safe but I'm no safety expert and no hacker.

Still the safest is to use a whitelist to pages that are trusted.

**Comment by feinstaub** [comment]
Thanks for this analysis.

1) So passing program parameters currently don't work, which is good.

2)
I also searched for how to access Firefox's temporary files and found this https://support.mozilla.org/en-US/questions/773444: "In Firefox it is called the cache, for details of its location type about:cache into the location bar and press enter.

For security reasons, files in the cache are given random file names, so it is difficult to view the contents. The CacheViewer etension may be of use to you." On my system the cache directory is located here: /home/user/.cache/mozilla/firefox/knitlu0q.default-1451735279581/cache2/entries/ and contains randomly named files. So, it seems hard to pick the right one and even if - none of the files are executable.

3)
I adapted your js fiddle to start /usr/bin/blender. And instead of launching it once in the timeout method I did it with a loop. After starting over 10 blender instances my system came to a halt and it was not even possible to switch to another terminal to kill the processes. So, that's a denial of service attack.

**Comment by AWolf81** [comment]
To 2)
Sounds like this should be OK but I'll have a look at it later.

To 3) 
Oh that's bad and we should add something to prevent this. We could do the following:
1. Add a preference for whitelisted executable files
2. Add a click rate limit for file links so you can only click the same link x-times before the addon blocks execution

I'd prefer 1. because we can disable all executable file links by default and only enable it after the program is added to the exe-whitelist-preference. Should be pretty easy to implement with a regular expression before opening the link.

**Comment by feinstaub** [comment]
I agree that the whitelist option is a good solution; with executables not allowed by default. If you use regular expression then a simple "*" for "all" is not possible. An empty regex would match all which is not intuitive. So maybe we would need two preferences: one to enable executable files at all and the second to specify the regex.

**Comment by AWolf81** [comment]
The notification for a blocked link is in my current working [branch](https://github.com/feinstaub/firefox_addon_local_filesystem_links/tree/sec-improve-is16) like this: `You're trying to open a not whitelisted executable file. Please check addon settings and try again.`

The new preference is looking like this:

    {
        "name": "whitelistExecutables",
        "title": "Add executable files that are allowed for opening",
        "description": "Any progam file you add to this whitelist (space separated) are enabled for opening by the addon (empty means all executables blocked, add * to allow all executables)",
        "type": "string",
        "value": ""
    }

The test is working like this:
1. Get the filename from the link
2. Check if it's an executable file (Windows *.exe and Linux /bin/filename) --> Linux not tested yet.
2. If executable, check if name is in whitelist or global enable pattern (*) is in whitelist.
3. If exe. isn't whitelisted show notification (You're trying to open... from above) and abort execution - otherwise open the file.

Windows is already working. Next I need to check if it's working in Ubuntu as well.

**Comment by AWolf81** [comment]
I can't launch any program in Ubunutu 14.04.3 and FF 45.0. What am I doing wrong? Or is there a security setting that's blocking the links? Any ideas?

I've tried these links:
``
    <a href="file:///usr/bin/subl">file:///usr/bin/subl (Linux open to sublime editor)</a><br/>
    <a href="file:///usr/bin/gnome-terminal">file:///usr/bin/gnome-terminal (Linux terminal)</a><br/>
``
First one opened the editor that's showing me the bash script and the second one is triggering no action.

(Can't test my code in Ubuntu at the moment.)

**Comment by feinstaub** [comment]
If you navigate to this jsfiddle https://jsfiddle.net/4bqs3dd7/1/ then gnome-terminal will be opened without user interaction.

One thing that came to me about the whiteliste preference: I wonder if there is a use case to have a white list at all? Maybe it is enough to just have executables enabled or disabled (latter would be default; for the first one it should written clear that this could be used to crash the system).

I can imagine one use case: someone creates a HTML page that serves as his personal launcher for applications. It would be a bit tedious to white list all his applications and then still there could be DOS attack.

**Comment by AWolf81** [comment]
Yes, I also think it's better to have only an enable for executables. I've added that.

I still can't launch a program in Ubuntu. Don't know why. I've also setup a new vm box with a fresh Ubuntu 15.10 (64bit) installation but still the same behaviour and I can't find any setting to change it. What Linux distribution / version do you use?

I think the detection of executables for Windows is OK now because I'm covering several file extensions (exe, bat, bin, msi, msp, mst, cmd & com). (Please let me know if I've missed a critical executable extension.)
But I think my detection in Ubuntu is weak at the moment. I'm only checking if the link is containing `/bin/filename` like in this [regex101](https://regex101.com/r/tA2dX7/1).
Do you see another way to detect if it's an executable? Do we need another pattern?

**Comment by feinstaub** [comment]
- I am using openSUSE 42.1 and FF 45.0
- Windows exe pattern looks fine
- Linux pattern: your regex covers /bin/*, /usr/bin/*, /usr/local/bin/*, /opt/*/bin/* which is good enough I think. Please make it also cover /usr/sbin/* for the super user commands. Ideally, one would check the executable (x) file attribute to determine if a file is executable.

**Comment by AWolf81** [comment]
OK, no problem. I've added `sbin` to the regex https://regex101.com/r/tA2dX7/2

Next I'll add it to the code. I'm also trying to add a check for the executable attribute after the path check for Linux. But I'm not sure if that's possible I need to read the api docs at MDN.

**Comment by feinstaub** [comment]
This is solved I guess.
