### ISSUE TITLE
support smb:// for MAC

### ISSUE THREAD

**Issue by feinstaub** [feinstaub/firefox_addon_local_filesystem_links#25]
reported by by BobJG22 on February 20, 2014 on https://addons.mozilla.org/en-US/firefox/addon/local-filesystem-links/:

"I have an asp.net / IIS application with links for opening network share folders. If I make the URL for the link "file://", then it works perfectly on the PC. On FireFox for the MAC, I see the "local filesystem links' folders, but nothing happens when I click on them.
The reason is, for the MAC, you need "smb://", not "file:'//".
Is there any way to have Local FileSystem Links work for "smb://" links the same way it does for "file://"?"

**Comment by amery** [comment]
`file://///server/foo` should be translated to `smb://server/foo` on both Linux and OSX.

**Comment by feinstaub** [comment]
Can you extend to the test suite page test/webserver/std1/issue.htm to reproduce the desired behaviour?

**Comment by feinstaub** [comment]
I will close old bugs. Is this still an issue? If yes please don't hesitate to reopen it.

**Comment by amery** [comment]
yes, this is still an issue. Linux doesn't support file:///// for cifs/smb, only smb://

**Comment by litatus** [comment]
In order to make it work in a MAC I use the "local path" of the shared folder, that it's in "/Volumes/".
Obviously I have to mount mi shared folder with smb (smb://192.168.4.33/DATEN) before. After that, it is accesible through /Volumes/DATEN, that means that my href is "file:///Volumes/DATEN/{folder}".
It works for me.
