### ISSUE TITLE
Klicking a file link's folder symbol launches that file

### ISSUE THREAD

**Issue by Peter0** [feinstaub/firefox_addon_local_filesystem_links#44]
I'm not quite shure if this is a duplicate of #32, but after I managed to get V0.99.39 up running by putting some directories in a 0.99.37-XPI file (ref. Hint on mozilla's rating page by Peter-0), I realized that there is another flaw:

**Observed behaviour:** Klicking on a folder symbol next to e.g. a PDF file opens that PDF in reader.
**Expected behaviour:** Klicking on a folder symbol opens the file's subdirectory in window's explorer and marks the very file.

Somewhere I've seen a proposal to open a **context menu** to get the choice between open file and open folder. IMHO this is superfluous, as the user have exactly this choice by clicking the original link or by clicking on the folder symbol directly next to the original link.

Thanks – Peter

**Comment by FoTo50** [comment]
Hi, not sure if this is the right place to post, but since I had same issue and tried to find a solution, I want to share what I found:
In the \*.xpi (v0.99.39b), there is a file ./lib/launch-local-process.js
Changing line 110 (the one right below "*if (localFile.isFile()) {*") from
**localFile.launch();**
to
**localFile.reveal();**
fixed the issue for me
Greetz
George

**Comment by feinstaub** [comment]
Yes, if https://github.com/feinstaub/firefox_addon_local_filesystem_links/issues/32 gets implemented your issue will be solved. Closed as duplicate.
