### ISSUE TITLE
Multi-process Firefox compatibility

### ISSUE THREAD

**Issue by feinstaub** [feinstaub/firefox_addon_local_filesystem_links#48]
For Q1 2016 there is an issue that maybe affects us. Quote:

Dear add-on developer,

You might have heard the news[1] that future versions of Firefox will run the browser UI separately from web content. This is called Multi-process Firefox (also "Electrolysis" or "e10s")[2], and it is scheduled for release in the first quarter of 2016[3].

If your add-on code accesses web content directly, using an overlay extension[4], a bootstrapped extension[5], or low-level SDK APIs[6] like window/utils or tabs/utils, then you will probably be affected.

To minimize the impact on users of your add-ons, we are urging you to test your add-ons[7] for compatibility. You can find documentation on how to make them compatible here[8].

Starting Nov. 24, 2015, we are available to assist you every Tuesday in the #addons channel on irc.mozilla.org[9]. Click here[10] to see the schedule. Whether you need help testing or making your add-ons compatible, we're here to help!

Sincerely,
The Add-ons Team

[1] https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/
[2] https://developer.mozilla.org/en-US/Firefox/Multiprocess_Firefox
[3] https://wiki.mozilla.org/Electrolysis#Schedule
[4] https://developer.mozilla.org/en-US/Add-ons/Overlay_Extensions
[5] https://developer.mozilla.org/en-US/Add-ons/Bootstrapped_extensions
[6] https://developer.mozilla.org/en-US/Add-ons/SDK/Low-Level_APIs
[7] https://developer.mozilla.org/en-US/Add-ons/Working_with_multiprocess_Firefox#Testing
[8] https://developer.mozilla.org/en-US/Add-ons/Working_with_multiprocess_Firefox#Updating_your_code
[9] irc://irc.mozilla.org/addons
[10] https://atsay.github.io/e10s_office_hours/

**Comment by AWolf81** [comment]
I think the plugin is affected because we're using the low-level API [content/worker](https://developer.mozilla.org/en-US/Add-ons/SDK/Low-Level_APIs/content_worker).

I have to check how to change the content-script to work with a frame-script. But first I'm [testing](https://developer.mozilla.org/en-US/Add-ons/Working_with_multiprocess_Firefox#Testing) with the latest nightly of FF if this is really affected 

If it's affected I think [this guide](https://developer.mozilla.org/en-US/Add-ons/Working_with_multiprocess_Firefox#Updating_your_code) will help to fix it.

**Comment by AWolf81** [comment]
Test with Windows 10 and FF Nightly 47.0a1 (2016-03-06) passed. No issues detected with-out shims.
To add the multiprocess to the plugin I've added this to the `package.json` (I'll add this later to master):

    "permissions": {
        "multiprocess": true
    },

Then I wasn't sure if it was correctly added into the `install.rdf` file. But this can be checked by opening the xpi file with Atom.io (or any text editor, maybe after unpacking) and view the RDF file. There will be a row with `<em:multiprocessCompatible>true</em:multiprocessCompatible>`. So addon is in compatible mode.

**Screenshot to see that multiprocess is enabled in Nightly FF:**
![Screenshot](http://i.imgur.com/cRASP6k.png)

To run the addon in nightly FF (after downloading & installing it from [here](https://nightly.mozilla.org/)) use `jpm run -b path-to-nightly\firefox.exe`

Now I need to check it with Linux/Ubuntu but I think that should work as well because we're using Addon-SDK (like described in [porting to addon SDK](https://developer.mozilla.org/en-US/Add-ons/Working_with_multiprocess_Firefox)).

**Comment by feinstaub** [comment]
Hi,
thanks for the work and detailed explanation. Sounds good.
