### ISSUE TITLE
Use font symbol (glyphicon) instead of image for Folder icon

### ISSUE THREAD

**Issue by MurzNN** [feinstaub/firefox_addon_local_filesystem_links#53]
Currently local_filesystem_links script adds folder icon via pixel image with fixed size, so with small font size they looks bad: http://i.imgur.com/p5MnkUl.png
Will be good replace image via font symbol (glyphicon), for example from bootstrap font: http://getbootstrap.com/components/ glyphicon-folder-close or from http://foundation.zurb.com/icon-fonts.html
It will be rendered via current font size, so will looks good.

**Comment by AWolf81** [comment]
Thanks for your feedback. It's already a [google material icon font](https://design.google.com/icons/).

Maybe I can change the css of the icon to have a better scalability. What's the font size of your link, so I can check it?

It should be easy to fix. I just have to make the font-size relative like following (!important is only needed if added in a css outside of the plugin):

    .aliensun-link-icon:after{
      font-size: 0.5em !important;
    }

At the moment the icon is fixed with 16px.

Until I have modified/checked the style a workaround would be to add the above css to your styles (if that's possible).

**Comment by MurzNN** [comment]
Maybe something like this https://jsfiddle.net/z36exhf9/1/ ?

**Comment by AWolf81** [comment]
Yes, that's looking good and scales nicely with the font-size. I'll add that later today.

**Comment by AWolf81** [comment]
OK, I've added it and I think it looks good now. 
![screenshot](http://img.ctrlv.in/img/16/03/01/56d5fae14c37d.png)

**Comment by feinstaub** [comment]
Thanks for using a font instead of a fixed-size image!

However, there are two things I noticed:
1) The uniform color reduces the contrast.
2) The color is too bright for my taste, so I can barely recognize the shape.

There are two reviews about the new icon:
- https://addons.mozilla.org/en-US/firefox/addon/local-filesystem-links/reviews/783017/
- https://addons.mozilla.org/en-US/firefox/addon/local-filesystem-links/reviews/783085

What do you think about this: instead of using a font, why not using an SVG image?

**Comment by MurzNN** [comment]
SVG image will be good solution too, but font symbol size will match size of other symbols, and size of SVG image we will must set manually, and, maybe, rendering many SVG will be slower that font symbol.

**Comment by MurzNN** [comment]
Updated version 0.99.42 from Mozilla repository is broken for me too, here is screenshot: http://i.imgur.com/BUQCj0p.jpg - seems that font loading is broken.

**Comment by AWolf81** [comment]
The issue with not showing the icon at all was because FF 38 doesn't support WOFF2 font by default so I've added the base64 for WOFF and that fixed the issue. So the icon should show with the latest master.

**To the color of the icon:**
Yes, you're right with the contrast. I think it is not bad but it could be better. What do you think would be adding a background circle an option to improve the contrast?

Please have a look at this [fiddle](https://jsfiddle.net/awolf2904/7rnw8pe9/).

The standard test page looks now like in the following screenshot (with my latest commit):
![screenshot new icons design](http://img.ctrlv.in/img/16/03/04/56d8d2f638726.png)

**Comment by feinstaub** [comment]
Thanks for the icon fix.

To the contrast issue: The circle seems to be a bit bloated to me. For usability it is an improvement to me. With respect to my design taste, it is not.

Alternative - less intrusive - solutions:
- change the color from yellow to brown or another color which is darker then yellow
- or add a shadow; this should be possible with CSS.

**Comment by feinstaub** [comment]
Here an example of the text shadow which I would prefer over the circle:

      <a href="#">text
         <i class="material-icons link-icon" style="text-shadow: 1px -1px #555"></i>
       </a>

**Comment by feinstaub** [comment]
Let's use "color: orange" for the folder symbol color.

**Comment by feinstaub** [comment]
This is even better:

style="text-shadow: -1px 0 black, 0 1px black, 1px 0 black, 0 -1px black; color: orange"

see https://jsfiddle.net/bkk7wm28/2/

(more fancy shadow tricks see here: https://www.w3.org/Style/Examples/007/text-shadow.en.html)

**Comment by AWolf81** [comment]
Yes, you're right. The circle is too bloated.

Good idea with the shadow and orange is OK.
I'd do the shadow a bit different. Like in this fiddle https://jsfiddle.net/awolf2904/bkk7wm28/3/

I think having a light drop shadow instead of the solid border is looking better.

**Comment by feinstaub** [comment]
Personally, I like having the border around the folder symbol because then the folder shape is more clearly visible. What about adding a shadow to the bordered icon (combining both solutions)? But I am also fine to go for your last proposal. It could be optimized at some later point in time.

**Comment by AWolf81** [comment]
Combining the border and a shadow would be probably also OK.
Maybe a gray border with shadow would look better but we can optimise that
later.

I'd like to improve the open containing folder issue first. I've already
started with it see branch with the issue number.

It's almost ready just the click handler in content script is not working
yet. Once that's ready I can trigger the reveal action.
Am 05.03.2016 02:24 schrieb "feinstaub" <notifications@github.com>:
