### ISSUE TITLE
folder icon is missing despite it is set in config

### ISSUE THREAD

**Issue by dj-turnbeutel** [feinstaub/firefox_addon_local_filesystem_links#62]
Hello develeopers for local filesystem links, it's a great addon in firefox and I use it every day. 

It seems that under firefox 38.0.1 the css class for html emelent i (.material-icons.link-aliensun-link-icon) is empty. So my local web page is showing up only the name (alt or title attribute i guess) for the missing images ("folder" and "folder_open"). Is there any way to let local filesystem links know the path to the icons? Here is my code snippet for relevant folder presentation:

<td id="mid">
<a href="file:///d:/Partners/20081/daivb/2016-01-04.txt" target="_blank">
<i class="material-icons aliensun-link-icon"></i>
</a>

Thanks in advance for your support.
Ole

**Comment by AWolf81** [comment]
Thanks for your feedback. 

This is issue is fixed (see issue [here](https://github.com/feinstaub/firefox_addon_local_filesystem_links/issues/53)) in the current master version and will be improved in the next release of the addon.

The problem was that FF 38 requires WOFF font format as well and not only WOFF2 font.

@feinstaub When do we update the version at mozilla gallery? I think we could do an update after closing the two open PRs.

**Comment by dj-turnbeutel** [comment]
Yeah Alex,

the @font-face hack did the job. 

Thank you so much and have a nice weekend.
Ole

**Comment by feinstaub** [comment]
@AWolf81 yes, I'll take a look at those. Please note that for at least #60 I did not get a notification. Please add my name when I shall review.
