### ISSUE TITLE
Request of some improvements

### ISSUE THREAD

**Issue by lmaodzedun** [feinstaub/firefox_addon_local_filesystem_links#65]
1. Links like «\link\random\" should be underlined and highlighted by blue color with using the HTML <a href=... syntax.
2. It would be great if direct links to file (like «\link\random\file.jpg») opens inside browser as option.
3. Addon needs extended Settings menu.
4. Russian localization (I can helps with it).

**Comment by AWolf81** [comment]
Thanks for your improvement ideas.

1. I've tried this before but I think it's not possible or very difficult becasue FF is handling those links directly. See this [fiddle](https://jsfiddle.net/awolf2904/2yh9w72m/). `/link/random/` is interpreted as relative url.

2. I have to check if we can add this as option so that images, pdfs etc. are opened in browser.

3. Where should that menu be located? In the addonbar? What options should be available there? In the latest master we have an icon in addonbar to easier access the addon settings page. We could also add a dropdown menu to that icon but it's more complicated then the standard preference page.
Icon in addonbar will looks like this:
![addon bar icon](https://raw.githubusercontent.com/feinstaub/firefox_addon_local_filesystem_links/master/doc/screenshots/Screenshot_active_addonbar.png)
4. OK, I'll implement this and once I've the setup ready I'll come back to you for Russian language support. I can add German language localization.

**Comment by AWolf81** [comment]
@lmaodzedun could you please translate the following [gist](https://gist.github.com/AWolf81/349aca151511d4a08b549327ca36ce37) to Russian?
I've created a branch for [localization](https://github.com/feinstaub/firefox_addon_local_filesystem_links/tree/localization-is-%2365).

**Comment by feinstaub** [comment]
@AWolf81 Hey, this is great, we got i18n! Thanks for the work!

**Comment by AWolf81** [comment]
@feinstaub No problem. I've also modified the thing with issue #41 in that branch (moved to index.js). Once I've the Russian translation I'll create a PR for checking if I haven't made any typos.

**Comment by AWolf81** [comment]
I think we can close this as all features will be added with version 0.99.47 (especially in browser open - context menu item & default link behaviour changeable to direct open).

If there is still something missing please let me know.
