### ISSUE TITLE
add config for default action "open" or "reveal"

### ISSUE THREAD

**Issue by dsheyp** [feinstaub/firefox_addon_local_filesystem_links#70]
Hi feinstaub

In my usecase for this great extension it would make sense to have the option to choose "reveal" as the default action when clicking a local filesystem link instead of opening the link. I hardcoded this into the extension but I would like to see this in an official release as an option in the configuration.

What do you think about that?

Regads
dshepy

**Comment by AWolf81** [comment]
Hi, thanks for your idea / use-case.

From my side this should be OK to add. @feinstaub what do you think? Should we add this as option.

What would we do with the icon? We could add the direct link open to the icon. Maybe we can also change the icon so it's clear that it is not the reveal function.

**Comment by feinstaub** [comment]
The option would be ok from my side.

@AWolf81: I had no time yet to fully review https://github.com/feinstaub/firefox_addon_local_filesystem_links/pull/66. But from what I saw I  think it is ok. So you can merge it. If you like, I would be happy if you would also

- update https://github.com/feinstaub/firefox_addon_local_filesystem_links/blob/master/CHANGELOG for  the upcoming version (which is "0.99.45")
- do some testing (or let other users test) as you think is enough for the QS
- create a new tag for the new version
- and then notify me so that I can do a final review and build and upload the new version to AMO.

Thanks again for your active participation in developing this addon.

**Comment by AWolf81** [comment]
OK, I've added the feature to branch [fb-70-open-reveal-option](https://github.com/feinstaub/firefox_addon_local_filesystem_links/tree/fb-70-open-reveal-option). Please have a look if it is working as expected.

The icon will change to an arrow with similar hover effect like the folder icon if the reveal is the action on link text click. Also the tooltips are modified at option change (just couldn't capture this in the screenshot)
![new icon](https://raw.githubusercontent.com/feinstaub/firefox_addon_local_filesystem_links/fb-70-open-reveal-option/doc/screenshots/Screenshot_new_feature_revealopen_icon.png)

The following option will be added to preference page:
![settings](https://raw.githubusercontent.com/feinstaub/firefox_addon_local_filesystem_links/fb-70-open-reveal-option/doc/screenshots/Screenshot_new_feature_revealopen_pref.png)

@feinstaub You're welcome. I really like to work at this addon becasue I'm still learning a lot and it's fun to implement new stuff.
To your mentioned points: 
I need to do some tests for this feature (e.g. check if dynamic links are working as expected). Then I can do a PR for this and afterwards I can do your mentioned points.

**Comment by dsheyp** [comment]
Hi!

Impressive how fast you reacted on my wish / idea :-) Thanks!

@AWolf81 I quickly tested your code and it worked for me the way it is coded. The only issue is when switching the radio buttons I observed an error in the console, saying it couldn't find the worker to receive this message. May be that's something to have a look into.

My question is about the reveal-action: I realized that for revealing the file name is always stripped off. (https://github.com/feinstaub/firefox_addon_local_filesystem_links/blob/fb-70-open-reveal-option/lib/launch-local-process.js#L155) Why is that? Wouldn't it be helpful for users if the file (if it exists) is highlighted when it is revealed e.g. in a folder with many files to prevent users having to scroll down in order to find the file they were looking for.

**Comment by AWolf81** [comment]
That's a good point. I'll check if highlighting is possible after revealing the folder.

The filename is stripped because it would give an error (file not found message instead of reveal) if the file doesn't exists. Maybe I can first check if the file exists and if we're revealing the folder we can then strip the filename if it is not existing.

**Comment by dsheyp** [comment]
Perfect, thanks!

Just one word about revealing that you might already know: I'm not sure about OS X but on Windows reveal() does excactly what you want. It opens File Explorer, navigates to the containing folder of a file, scrolls down (if it has to) and highlights/selects the file (without executing or opening the file). But again, I'm not sure what reveal exactly does on OS X and Linux. But if it does the same thing as on Windows I think it would be best to check for file existence first and if it returns true then reveal the file and in case the file doesn't exist strip of the file name and reveal the files parent folder.

The advantage of reveal for my usecase is, that a file is highlighted/selected before actually opening it, which gives the user the opportunity to look at the file size and other file properties before actually opening it. If the file was a huge Photoshop file of let's say 5 GB on a NAS the user could decide to not open it and instead opening a thumbnail of 200 kB that might exist next to the actual file.

**Comment by AWolf81** [comment]
@dsheyp Thanks for explaining your use-case in detail. I've fixed the reveal so now the revealed file will be selected if it exists. Works for Windows and Linux (tested with Ubuntu 15.10). OS X test not possible for me at the moment because I don't have a Mac and I can't find a Virtual Machine image where I could test the plugin.

I think we can close this issue.

@feinstaub Please review my changes. I've added the changelog to master and created the tag.
For this issue I've created a PR to write down what I've tested. See PR #71.

I think I've tested everything. I've also fixed the testing a minute ago. It failed because the path to index.js was not modified. Now 32 of 32 tests passed.
(Just some log messages as warnings at the test. Should be no problem. Later, I'll check if the warnings can be reduced.)

**Comment by feinstaub** [comment]
@AWolf81:
- the code style issues I mentioned as inline comments can be fixed later
- It seems that the behaviour of the new option "New option to change default text link click behaviour (open/reveal)" is reversed.

**Comment by AWolf81** [comment]
@feinstaub:
* **Code style**: Yes, you're right. Code style needs to be improved. I'm currently working on issue #22 and there I'll add [jslint](http://www.jslint.com/) with gulp. So we can check the style. It's probably not exactly crockford js style but we could adjust it as needed. 
* I can't see this behaviour. The arrow like icon opens the file and the folder icon reveals the folder. Tested with Linux and Windows. e.g. tested with this link in Ubuntu: [file:///~/tmp/print.pdf](file:///~/tmp/print.pdf). Where have you detected this behaviour or is it at every icon?
* I also see this issue in Linux and I'll check why this happens.
* OK, I create the next tags with-out "v". I've just created it like all other tags and I'll use the semver number scheme.
* Yes, addon bar icon is very usable. I've installed the latest released version for testing and immediately missed this feature.
