### ISSUE TITLE
Plugin also converts Invisible Links

### ISSUE THREAD

**Issue by skydel0** [feinstaub/firefox_addon_local_filesystem_links#74]
The plugin should not convert invisible links that only crash the firefox if theres more than 300 ore 400 links.

**Comment by AWolf81** [comment]
Thanks for your feedback. 

Yes, it will add the icon also to hidden links. As a quick work-around until we fixed this you could remove the links from the page instead of hiding them. 
But I'm not sure if this fixes the problem because it sounds like the adding of the icon is too heavy to handle 300 to 400 links in one page. (Disabling the icon should also work if that's an option.)

I'll check if I can add something to disable the adding of the icon if it is hidden. I think the [line]( https://github.com/feinstaub/firefox_addon_local_filesystem_links/blob/master/data/js/fileLinkAddonContent.js#L159) is the right position to add a check if the container is displayed or not. I need to check if this can improve the behaviour.

You're hiding the links with `display: none` at the parent element or do you hide each a-tag of the link? Just to be sure I'm testing this correctly. (I think I will test it with both possible ways.)

**Comment by skydel0** [comment]
We used display: none.

Now i Display the Results on difrent pages and then much results are not the problem. 

But i don't like this solution.

**Comment by AWolf81** [comment]
@skydel0 
I have good news for you. 

I'll changed the jQuery code for adding the icon to vanilla javascript and now the icons are visible after around one second for a test page with 800 file links. (Doesn't matter if hidden icons or not. It still adds the icon to hidden elements but I think that's OK because it's really complicated to add it later.)
Before my change it took ~45 seconds and FF was almost crashing and not responsive.

There is still a time were FF is not responsive but now it is around 2 seconds were the framerate drops close to zero. 

You can test the code at the branch [fix-issue-74](https://github.com/feinstaub/firefox_addon_local_filesystem_links/tree/fix-issue-74).

Thanks again for your feedback because it helped a lot to improve the performance of the addon.

**Comment by AWolf81** [comment]
This will be improved with version 0.99.47. (not available at gallery yet.)

Invisible icons are still added because that's easier to handle for the addon. But with the improvement that should be no problem.

I'm closing this. If you're still having the issue with the next version please let me know.
