### ISSUE TITLE
a script on this page may be busy or it may have stopped responding

### ISSUE THREAD

**Issue by guenterneust** [feinstaub/firefox_addon_local_filesystem_links#79]
Usually, this addon work just fine for me.
But when I open a page with lots of local filesystem links (I tried wit about 1500), I get the window which begins with:
_a script on this page may be busy or it may have stopped responding_
complaining about jquery when loading the page.
If I click stop script, the links are working.
If I disable the addon, the page loads just fine, but I can't open the local files.
Is there any way to solve this issue?

**Comment by AWolf81** [comment]
Thanks for your feedback.

The issue #74 is related. This issue will be improved with a next release of the addon (see PR #76). The improvement is not perfect because there is still a small lag where brower is not responsive (around 2 seconds for 800 file links) but I think that's acceptable.

A work-around would be to disable the icon in the preferences (if that's an option for you). If this is no option, the best is to wait for the performance improvement in the next release.

**Comment by guenterneust** [comment]
Thank you.
The workaround of disabling the icons solves my issue - now I can open pages with about 5000 local links without problems.

**Comment by guenterneust** [comment]
Hello
I use this addon on my PC at work when I use Firefox to view a tracker for change notifications, with about 100-500 change notifications each year, the system being in use for 7 years, each having up to 3 local links.By disabling the icons, I can view the entire history at once, and the links can be opened as expected.
Thank you
Günter
