### ISSUE TITLE
Bug links with European accents

### ISSUE THREAD

**Issue by santimauro** [feinstaub/firefox_addon_local_filesystem_links#84]
Bug in the new version concerning links with European accents : 
![image](https://cloud.githubusercontent.com/assets/8707041/23748951/197d8c74-04c6-11e7-9938-c968fbcf39ef.png)

"é" replaced by "A9"

**Comment by AWolf81** [comment]
Thanks for filing this issue. 
I'll check what change caused this and try to fix it asap.
I have to look at the code but probably just an encoding issue and hopefully I can quickly fix this. 

I've missed this because there's no test case for those characters. 
I'll also add one so this won't happen again.

**Comment by AWolf81** [comment]
This issue will be fixed once the PR #85 is merged and a new version is published to Mozilla gallery.

**Comment by AWolf81** [comment]
OK, we can close this issue.
It's fixed with the version 0.99.47 which is available in Mozilla gallery now.

If there are still problems, just add them here and I'll have a look at it.
